# Generated by Django 5.2.8 on 2025-11-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name": "category"},
        ),
    ]
