# Generated by Django 5.2.8 on 2025-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name": "Category"},
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.category"
            ),
        ),
    ]
